insert into tipsmoto.users (name,
                            phone,
                            email,
                            email_verified_at,
                            password,
                            two_factor_secret,
                            two_factor_recovery_codes,
                            two_factor_confirmed_at,
                            status,
                            remember_token,
                            current_team_id,
                            created_at,
                            updated_at,
                            deleted_at)
select name,
       phone,
       email,
       email_verified_at,
       password,
       two_factor_secret,
       two_factor_recovery_codes,
       two_factor_confirmed_at,
       status,
       remember_token,
       current_team_id,
       created_at,
       updated_at,
       deleted_at
from copy_db.copy_users where not id = 1;


